name: flashcards_reader
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_information: ^0.0.4
  # <uses-permission android:name="android.permission.READ_PHONE_STATE" /> need to device_information correct work

  intro: ^1.2.3
  path: ^1.8.3
  external_path: ^1.0.3
  cupertino_icons: ^1.0.2
  watcher: ^1.0.2
  path_provider: ^2.0.14
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  flutter_staggered_animations: ^1.1.1
  bloc: ^8.1.1
  flutter_tts: ^3.6.3

  flutter_bloc: ^8.1.2
  overlay_support: ^2.1.0
  intl: ^0.18.1
  quick_actions: ^1.0.2
  pick_or_save: ^2.2.4
  flutter_dialogs: ^3.0.0

  # READER dependencies
  pdfx: ^2.4.0
  syncfusion_flutter_pdfviewer: ^22.2.11
  fb2_parse: ^1.0.1
  epubx: ^4.0.0
  html: ^0.15.4
  archive: ^3.3.7
  xml: ^6.3.0
  flutter_native_text_view: ^0.1.1
  liquid_progress_indicator_v2: ^0.5.0
  share_plus: ^7.1.0
  epub_view: ^3.2.0
  flutter_html: ^3.0.0-beta.2

  cached_network_image: ^3.0.0
  connectivity: ^3.0.6
  curved_navigation_bar: ^1.0.3
  dio: ^4.0.6
  flutter_svg: ^2.0.0+1
  flutter_spinkit: ^5.0.0
  http: ^1.1.0
  lottie: ^1.4.3
  material_design_icons_flutter: ^5.0.6996
  permission_handler: ^10.4.1
  share: ^2.0.4
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.2
  integration_test:
    sdk: flutter

  translator:
    path: local_packages/translator

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/flutter_logo.png
    - assets/images/add_circle.png
    - assets/images/quiz.png
    - assets/images/empty.png
    - assets/book/quotes_skin.png
    - assets/book/quotes.txt
    - assets/guide/1.png
    - assets/guide/2.png
    - assets/guide/3.png
    - assets/test/test.epub
    - assets/test/test.mobi
    - assets/test/test.pdf
    - assets/test/test.fb2
    # fb 2 on zip
    - assets/test/test.zip

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Gideon_Roman
      fonts:
        - asset: assets/fonts/GideonRoman-Regular.ttf

    - family: Noto_Serif
      fonts:
        - asset: assets/fonts/NotoSerifDisplay-Regular.ttf

    - family: Redressed
      fonts:
        - asset: assets/fonts/Redressed-Regular.ttf
