// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEFiQwSAxe34jr5AzBTYKE0qEgBj8xqC4',
    appId: '1:836076557370:web:826045f29235d5172c9103',
    messagingSenderId: '836076557370',
    projectId: 'flash-reader',
    authDomain: 'flash-reader.firebaseapp.com',
    storageBucket: 'flash-reader.appspot.com',
    measurementId: 'G-T6VRR1RZZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJjR75nnR5AbOYoNepYs-O4HkzpwVJfM0',
    appId: '1:836076557370:android:760d14f7eef319eb2c9103',
    messagingSenderId: '836076557370',
    projectId: 'flash-reader',
    storageBucket: 'flash-reader.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTlZjNu5pj9O9KlVCf-ykgLlR-7-FIJRg',
    appId: '1:836076557370:ios:c980e8943438556e2c9103',
    messagingSenderId: '836076557370',
    projectId: 'flash-reader',
    storageBucket: 'flash-reader.appspot.com',
    iosBundleId: 'com.example.flashcardsReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTlZjNu5pj9O9KlVCf-ykgLlR-7-FIJRg',
    appId: '1:836076557370:ios:c980e8943438556e2c9103',
    messagingSenderId: '836076557370',
    projectId: 'flash-reader',
    storageBucket: 'flash-reader.appspot.com',
    iosBundleId: 'com.example.flashcardsReader',
  );
}
